server:
  port: 8090

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger [%mdc{}] - %msg%n"
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

springdoc:
  swagger-ui:
    use-root-path: true
    disable-swagger-default-url: true
